name: ggnet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - fastapi==0.104.1
      - uvicorn[standard]==0.24.0
      - sqlalchemy==2.0.23
      - alembic==1.12.1
      - asyncpg==0.29.0
      - aiosqlite==0.19.0
      - python-jose[cryptography]==3.3.0
      - passlib[bcrypt]==1.7.4
      - python-multipart==0.0.6
      - redis==5.0.1
      - aioredis==2.0.1
      - httpx==0.25.2
      - aiofiles==23.2.1
      - pydantic==2.5.0
      - pydantic-settings==2.1.0
      - structlog==23.2.0
      - sentry-sdk[fastapi]==1.38.0
      - slowapi==0.1.9
      - python-magic==0.4.27
      - pillow==10.1.0
      - psutil>=5.9.5
      - click==8.1.7
      - rich==13.7.0
      - typer==0.9.0
      - black==23.11.0
      - isort==5.12.0
      - flake8==6.1.0
      - mypy==1.7.1
      - mkdocs==1.5.3
      - mkdocs-material==9.4.8
      # TEST dependencies
      - pytest==8.4.2
      - pytest-asyncio==0.23.6
      - pytest-cov==4.1.0
      - factory-boy==3.3.0
      - faker==20.1.0
      - pydantic[email]==2.5.0
