"""Alembic migrations must match the models and work in both directions."""

from __future__ import annotations

import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import inspect, text

from app.db.session import make_engine

from .conftest import alembic_config


def test_models_match_migrations(db_url):
    """`alembic check`: fails if a model changed without a new migration."""
    try:
        command.check(alembic_config(db_url))
    except AutogenerateDiffsDetected as e:
        pytest.fail(f"Models and migrations differ; a new migration is needed:\n{e}")


def test_downgrade_and_upgrade_again(db_url):
    cfg = alembic_config(db_url)
    command.downgrade(cfg, "base")
    engine = make_engine(db_url)
    assert set(inspect(engine).get_table_names()) == {"alembic_version"}
    command.upgrade(cfg, "head")
    assert {"machines", "game_disks"} <= set(inspect(engine).get_table_names())
    engine.dispose()


def test_foreign_keys_enforced(db_url):
    """SQLite must actually check foreign keys."""
    engine = make_engine(db_url)
    with engine.connect() as conn:
        with pytest.raises(Exception, match="FOREIGN KEY"):
            conn.execute(text(
                "INSERT INTO machines (name, mode, initiator_iqn, game_disk_id, status, "
                "created_at, updated_at) VALUES ('pc01', 'disk', 'iqn.x:pc01', 999, 'idle', "
                "CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
            ))
    engine.dispose()


def test_make_engine_creates_sqlite_directory(tmp_path):
    db = tmp_path / "nested" / "dir" / "ggnet.db"
    engine = make_engine(f"sqlite:///{db}")
    with engine.connect() as conn:
        conn.execute(text("SELECT 1"))
    engine.dispose()
    assert db.exists()
