"""machines and game_disks

Revision ID: 0001
Revises: 
Create Date: 2026-10-07 14:56:13.772667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_disks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('zvol_path', sa.String(length=255), nullable=False),
    sa.Column('size_gb', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_disks')),
    sa.UniqueConstraint('name', name=op.f('uq_game_disks_name')),
    sa.UniqueConstraint('zvol_path', name=op.f('uq_game_disks_zvol_path'))
    )
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('mode', sa.Enum('disk', 'boot', name='machinemode', native_enum=False, length=16), nullable=False),
    sa.Column('initiator_iqn', sa.String(length=223), nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=True),
    sa.Column('game_disk_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('idle', 'provisioned', 'error', name='machinestatus', native_enum=False, length=16), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('clone_zvol', sa.String(length=255), nullable=True),
    sa.Column('clone_snapshot', sa.String(length=320), nullable=True),
    sa.Column('iscsi_target_iqn', sa.String(length=223), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_disk_id'], ['game_disks.id'], name=op.f('fk_machines_game_disk_id_game_disks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_machines')),
    sa.UniqueConstraint('initiator_iqn', name=op.f('uq_machines_initiator_iqn')),
    sa.UniqueConstraint('mac', name=op.f('uq_machines_mac')),
    sa.UniqueConstraint('name', name=op.f('uq_machines_name'))
    )
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machines_game_disk_id'), ['game_disk_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machines_game_disk_id'))

    op.drop_table('machines')
    op.drop_table('game_disks')
    # ### end Alembic commands ###
