"""agent heartbeat fields

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-07 17:28:45.301271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('agent_version', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('reported_iqn', sa.String(length=223), nullable=True))
        batch_op.add_column(sa.Column('iscsi_connected', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_column('iscsi_connected')
        batch_op.drop_column('reported_iqn')
        batch_op.drop_column('agent_version')
        batch_op.drop_column('last_seen_at')

    # ### end Alembic commands ###
