"""initial_migration_create_all_tables

Revision ID: 9d9e5558e847
Revises: 
Create Date: 2025-10-06 21:03:37.864463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d9e5558e847'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='userstatus'), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('LOGIN', 'LOGOUT', 'LOGIN_FAILED', 'PASSWORD_CHANGED', 'USER_CREATED', 'USER_UPDATED', 'USER_DELETED', 'USER_LOCKED', 'USER_UNLOCKED', 'IMAGE_UPLOADED', 'IMAGE_DOWNLOADED', 'IMAGE_CONVERTED', 'IMAGE_DELETED', 'IMAGE_SCANNED', 'MACHINE_CREATED', 'MACHINE_UPDATED', 'MACHINE_DELETED', 'MACHINE_ONLINE', 'MACHINE_OFFLINE', 'TARGET_CREATED', 'TARGET_UPDATED', 'TARGET_DELETED', 'TARGET_ACTIVATED', 'TARGET_DEACTIVATED', 'SESSION_STARTED', 'SESSION_STOPPED', 'SESSION_ERROR', 'BOOT_INITIATED', 'BOOT_COMPLETED', 'BOOT_FAILED', 'BACKUP_CREATED', 'BACKUP_RESTORED', 'CONFIG_CHANGED', 'SERVICE_STARTED', 'SERVICE_STOPPED', 'UNAUTHORIZED_ACCESS', 'PERMISSION_DENIED', 'SUSPICIOUS_ACTIVITY', 'VIRUS_DETECTED', name='auditaction'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='auditseverity'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('resource_name', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_ip_address'), 'audit_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_session_id'), 'audit_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_severity'), 'audit_logs', ['severity'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_username'), 'audit_logs', ['username'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('format', sa.Enum('VHD', 'VHDX', 'RAW', 'QCOW2', 'VMDK', 'VDI', name='imageformat'), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('virtual_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('compressed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADING', 'PROCESSING', 'CONVERTING', 'READY', 'ERROR', 'DELETED', name='imagestatus'), nullable=False),
    sa.Column('image_type', sa.Enum('SYSTEM', 'GAME', 'DATA', 'TEMPLATE', name='imagetype'), nullable=False),
    sa.Column('checksum_md5', sa.String(length=32), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('virus_scanned', sa.Boolean(), nullable=False),
    sa.Column('virus_scan_result', sa.String(length=50), nullable=True),
    sa.Column('os_type', sa.String(length=50), nullable=True),
    sa.Column('os_version', sa.String(length=100), nullable=True),
    sa.Column('architecture', sa.String(length=20), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processing_log', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('converted_from_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['converted_from_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_index(op.f('ix_images_name'), 'images', ['name'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('ip_address', sa.String(length=15), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('cpu_info', sa.String(length=500), nullable=True),
    sa.Column('memory_mb', sa.Integer(), nullable=True),
    sa.Column('disk_info', sa.Text(), nullable=True),
    sa.Column('gpu_info', sa.String(length=500), nullable=True),
    sa.Column('boot_mode', sa.Enum('LEGACY', 'UEFI', 'UEFI_SECURE', name='bootmode'), nullable=False),
    sa.Column('secure_boot_enabled', sa.Boolean(), nullable=False),
    sa.Column('uefi_firmware', sa.String(length=100), nullable=True),
    sa.Column('pxe_enabled', sa.Boolean(), nullable=False),
    sa.Column('ipxe_script_url', sa.String(length=500), nullable=True),
    sa.Column('boot_priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'RETIRED', name='machinestatus'), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_boot', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('room', sa.String(length=100), nullable=True),
    sa.Column('rack_position', sa.String(length=50), nullable=True),
    sa.Column('asset_tag', sa.String(length=100), nullable=True),
    sa.Column('auto_boot', sa.Boolean(), nullable=False),
    sa.Column('wake_on_lan', sa.Boolean(), nullable=False),
    sa.Column('power_management', sa.Boolean(), nullable=False),
    sa.Column('custom_config', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('boot_count', sa.Integer(), nullable=False),
    sa.Column('total_uptime_hours', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('maintenance_notes', sa.Text(), nullable=True),
    sa.Column('next_maintenance', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_asset_tag'), 'machines', ['asset_tag'], unique=False)
    op.create_index(op.f('ix_machines_hostname'), 'machines', ['hostname'], unique=False)
    op.create_index(op.f('ix_machines_id'), 'machines', ['id'], unique=False)
    op.create_index(op.f('ix_machines_ip_address'), 'machines', ['ip_address'], unique=False)
    op.create_index(op.f('ix_machines_mac_address'), 'machines', ['mac_address'], unique=True)
    op.create_index(op.f('ix_machines_name'), 'machines', ['name'], unique=False)
    op.create_table('targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=False),
    sa.Column('iqn', sa.String(length=255), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('initiator_iqn', sa.String(length=255), nullable=False),
    sa.Column('lun_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ERROR', 'PENDING', name='targetstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targets_id'), 'targets', ['id'], unique=False)
    op.create_index(op.f('ix_targets_iqn'), 'targets', ['iqn'], unique=True)
    op.create_index(op.f('ix_targets_target_id'), 'targets', ['target_id'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('session_type', sa.Enum('DISKLESS_BOOT', 'MAINTENANCE', 'TESTING', name='sessiontype'), nullable=False),
    sa.Column('status', sa.Enum('STARTING', 'ACTIVE', 'STOPPING', 'STOPPED', 'ERROR', 'TIMEOUT', name='sessionstatus'), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('client_ip', sa.String(length=15), nullable=True),
    sa.Column('client_mac', sa.String(length=17), nullable=True),
    sa.Column('server_ip', sa.String(length=15), nullable=False),
    sa.Column('boot_method', sa.String(length=50), nullable=True),
    sa.Column('boot_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('os_load_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ready_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('boot_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('os_load_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('total_startup_seconds', sa.Integer(), nullable=True),
    sa.Column('peak_memory_mb', sa.Integer(), nullable=True),
    sa.Column('peak_cpu_percent', sa.Float(), nullable=True),
    sa.Column('network_bytes_sent', sa.BigInteger(), nullable=True),
    sa.Column('network_bytes_received', sa.BigInteger(), nullable=True),
    sa.Column('disk_bytes_read', sa.BigInteger(), nullable=True),
    sa.Column('disk_bytes_written', sa.BigInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('boot_config', sa.JSON(), nullable=True),
    sa.Column('environment_vars', sa.JSON(), nullable=True),
    sa.Column('target_iqn', sa.String(length=255), nullable=True),
    sa.Column('target_portal', sa.String(length=255), nullable=True),
    sa.Column('initiated_by', sa.String(length=100), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('health_check_interval', sa.Integer(), nullable=False),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_session_id'), 'sessions', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_session_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_targets_target_id'), table_name='targets')
    op.drop_index(op.f('ix_targets_iqn'), table_name='targets')
    op.drop_index(op.f('ix_targets_id'), table_name='targets')
    op.drop_table('targets')
    op.drop_index(op.f('ix_machines_name'), table_name='machines')
    op.drop_index(op.f('ix_machines_mac_address'), table_name='machines')
    op.drop_index(op.f('ix_machines_ip_address'), table_name='machines')
    op.drop_index(op.f('ix_machines_id'), table_name='machines')
    op.drop_index(op.f('ix_machines_hostname'), table_name='machines')
    op.drop_index(op.f('ix_machines_asset_tag'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_images_name'), table_name='images')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_audit_logs_username'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_severity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_session_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_ip_address'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

