"""
Windows Registry Script Management API
Manages Windows registry scripts for diskless boot configuration
"""

from typing import Optional, List, Dict, Any
from fastapi import APIRouter, Depends, HTTPException, status, Body
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from pydantic import BaseModel, ConfigDict
from datetime import datetime
from pathlib import Path
import structlog
import json

from app.core.dependencies import get_db, get_current_user, require_operator
from app.core.config import get_settings
from app.models.user import User
from app.models.machine import Machine
from app.models.image import Image
from app.core.exceptions import NotFoundError

router = APIRouter(prefix="/windows-registry", tags=["windows-registry"])
logger = structlog.get_logger()
settings = get_settings()


class RegistryEntry(BaseModel):
    """Windows registry entry"""
    key: str  # e.g., "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters"
    value_name: str
    value_type: str  # "REG_SZ", "REG_DWORD", "REG_QWORD", "REG_MULTI_SZ", "REG_EXPAND_SZ"
    value: Any
    description: Optional[str] = None


class RegistryScript(BaseModel):
    """Windows registry script"""
    name: str
    description: Optional[str] = None
    entries: List[RegistryEntry]
    machine_id: Optional[int] = None
    image_id: Optional[int] = None
    apply_on_boot: bool = True


class RegistryScriptResponse(BaseModel):
    """Response model for registry script"""
    id: int
    name: str
    description: Optional[str]
    entries: List[RegistryEntry]
    machine_id: Optional[int]
    image_id: Optional[int]
    apply_on_boot: bool
    script_content: str
    created_at: datetime
    updated_at: datetime
    
    model_config = ConfigDict(from_attributes=True)


class RegistryScriptCreate(BaseModel):
    """Request model for creating registry script"""
    name: str
    description: Optional[str] = None
    entries: List[RegistryEntry]
    machine_id: Optional[int] = None
    image_id: Optional[int] = None
    apply_on_boot: bool = True


def generate_registry_script(entries: List[RegistryEntry]) -> str:
    """Generate Windows .reg file content from registry entries"""
    lines = ["Windows Registry Editor Version 5.00", ""]
    
    current_key = None
    for entry in entries:
        if entry.key != current_key:
            if current_key is not None:
                lines.append("")
            lines.append(f"[{entry.key}]")
            current_key = entry.key
        
        if entry.value_type == "REG_SZ":
            value = entry.value.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'"{entry.value_name}"="{value}"')
        elif entry.value_type == "REG_DWORD":
            lines.append(f'"{entry.value_name}"=dword:{entry.value:08x}')
        elif entry.value_type == "REG_QWORD":
            lines.append(f'"{entry.value_name}"=hex(b):{entry.value:016x}')
        elif entry.value_type == "REG_MULTI_SZ":
            if isinstance(entry.value, list):
                values = "\\0".join(str(v).replace("\\", "\\\\") for v in entry.value)
                lines.append(f'"{entry.value_name}"=hex(7):{values}\\0\\0')
        elif entry.value_type == "REG_EXPAND_SZ":
            value = entry.value.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'"{entry.value_name}"=hex(2):{value}')
    
    return "\n".join(lines)


def generate_powershell_script(entries: List[RegistryEntry]) -> str:
    """Generate PowerShell script to apply registry entries"""
    lines = [
        "# Windows Registry Configuration Script",
        "# Generated by GGnet Diskless Server",
        "",
        "$ErrorActionPreference = 'Stop'",
        ""
    ]
    
    for entry in entries:
        if entry.description:
            lines.append(f"# {entry.description}")
        
        key_path = entry.key.replace("HKEY_LOCAL_MACHINE", "HKLM:")
        
        if entry.value_type == "REG_SZ":
            value_str = entry.value.replace("'", "''")
            lines.append(f'Set-ItemProperty -Path "{key_path}" -Name "{entry.value_name}" -Value "{value_str}" -Type String')
        elif entry.value_type == "REG_DWORD":
            lines.append(f'Set-ItemProperty -Path "{key_path}" -Name "{entry.value_name}" -Value {entry.value} -Type DWord')
        elif entry.value_type == "REG_QWORD":
            lines.append(f'Set-ItemProperty -Path "{key_path}" -Name "{entry.value_name}" -Value {entry.value} -Type QWord')
        elif entry.value_type == "REG_MULTI_SZ":
            if isinstance(entry.value, list):
                values = ", ".join(f'"{v}"' for v in entry.value)
                lines.append(f'Set-ItemProperty -Path "{key_path}" -Name "{entry.value_name}" -Value @({values}) -Type MultiString')
        
        lines.append("")
    
    return "\n".join(lines)


# In-memory storage for registry scripts (in production, use database)
_registry_scripts: Dict[int, Dict[str, Any]] = {}
_script_counter = 0


@router.post("", response_model=RegistryScriptResponse, status_code=status.HTTP_201_CREATED)
async def create_registry_script(
    script_data: RegistryScriptCreate,
    current_user: User = Depends(require_operator),
    db: AsyncSession = Depends(get_db)
):
    """Create a new Windows registry script"""
    global _script_counter
    
    # Validate machine_id if provided
    if script_data.machine_id:
        result = await db.execute(
            select(Machine).where(Machine.id == script_data.machine_id)
        )
        if not result.scalar_one_or_none():
            raise NotFoundError(f"Machine with ID {script_data.machine_id} not found")
    
    # Validate image_id if provided
    if script_data.image_id:
        result = await db.execute(
            select(Image).where(Image.id == script_data.image_id)
        )
        if not result.scalar_one_or_none():
            raise NotFoundError(f"Image with ID {script_data.image_id} not found")
    
    # Generate script content
    reg_content = generate_registry_script(script_data.entries)
    ps_content = generate_powershell_script(script_data.entries)
    
    _script_counter += 1
    script_id = _script_counter
    
    script_record = {
        "id": script_id,
        "name": script_data.name,
        "description": script_data.description,
        "entries": [entry.model_dump() for entry in script_data.entries],
        "machine_id": script_data.machine_id,
        "image_id": script_data.image_id,
        "apply_on_boot": script_data.apply_on_boot,
        "reg_content": reg_content,
        "ps_content": ps_content,
        "created_at": datetime.utcnow(),
        "updated_at": datetime.utcnow(),
        "created_by": current_user.id
    }
    
    _registry_scripts[script_id] = script_record
    
    logger.info(
        "Registry script created",
        script_id=script_id,
        name=script_data.name,
        entries_count=len(script_data.entries)
    )
    
    return RegistryScriptResponse(
        id=script_id,
        name=script_data.name,
        description=script_data.description,
        entries=script_data.entries,
        machine_id=script_data.machine_id,
        image_id=script_data.image_id,
        apply_on_boot=script_data.apply_on_boot,
        script_content=reg_content,
        created_at=script_record["created_at"],
        updated_at=script_record["updated_at"]
    )


@router.get("", response_model=List[RegistryScriptResponse])
async def list_registry_scripts(
    machine_id: Optional[int] = None,
    image_id: Optional[int] = None,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """List all registry scripts with optional filtering"""
    scripts = list(_registry_scripts.values())
    
    if machine_id:
        scripts = [s for s in scripts if s.get("machine_id") == machine_id]
    
    if image_id:
        scripts = [s for s in scripts if s.get("image_id") == image_id]
    
    return [
        RegistryScriptResponse(
            id=s["id"],
            name=s["name"],
            description=s.get("description"),
            entries=[RegistryEntry(**e) for e in s["entries"]],
            machine_id=s.get("machine_id"),
            image_id=s.get("image_id"),
            apply_on_boot=s.get("apply_on_boot", True),
            script_content=s["reg_content"],
            created_at=s["created_at"],
            updated_at=s["updated_at"]
        )
        for s in scripts
    ]


@router.get("/{script_id}", response_model=RegistryScriptResponse)
async def get_registry_script(
    script_id: int,
    format: str = "reg",  # "reg" or "ps"
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Get a specific registry script"""
    if script_id not in _registry_scripts:
        raise NotFoundError(f"Registry script with ID {script_id} not found")
    
    script = _registry_scripts[script_id]
    
    script_content = script["reg_content"] if format == "reg" else script["ps_content"]
    
    return RegistryScriptResponse(
        id=script["id"],
        name=script["name"],
        description=script.get("description"),
        entries=[RegistryEntry(**e) for e in script["entries"]],
        machine_id=script.get("machine_id"),
        image_id=script.get("image_id"),
        apply_on_boot=script.get("apply_on_boot", True),
        script_content=script_content,
        created_at=script["created_at"],
        updated_at=script["updated_at"]
    )


@router.get("/machine/{machine_id}/script", response_model=RegistryScriptResponse)
async def get_machine_registry_script(
    machine_id: int,
    format: str = "reg",
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Get registry script for a specific machine"""
    # Find script for this machine
    scripts = [s for s in _registry_scripts.values() if s.get("machine_id") == machine_id]
    
    if not scripts:
        raise NotFoundError(f"No registry script found for machine {machine_id}")
    
    # Get the most recent script
    script = max(scripts, key=lambda s: s["updated_at"])
    
    script_content = script["reg_content"] if format == "reg" else script["ps_content"]
    
    return RegistryScriptResponse(
        id=script["id"],
        name=script["name"],
        description=script.get("description"),
        entries=[RegistryEntry(**e) for e in script["entries"]],
        machine_id=script.get("machine_id"),
        image_id=script.get("image_id"),
        apply_on_boot=script.get("apply_on_boot", True),
        script_content=script_content,
        created_at=script["created_at"],
        updated_at=script["updated_at"]
    )

