name: Python Package using Conda

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.11
          activate-environment: base
          environment-file: environment.yml
          use-mamba: false

      - name: Set PYTHONPATH for tests
        run: echo "PYTHONPATH=$(pwd)/backend" >> $GITHUB_ENV

      - name: Lint with flake8
        run: |
          conda run -n base flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          conda run -n base flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests
        run: conda run -n base pytest tests -v --disable-warnings --cov=app
