name: Python Package using Conda

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.11
        environment-file: environment.yml
        activate-environment: base
        use-mamba: false
        # shell: bash

    - name: Lint with flake8
      run: |
        cd backend
        export PYTHONPATH=$(pwd)
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate base
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run backend tests
      run: |
        cd backend
        export PYTHONPATH=$(pwd)
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate base
        pytest tests -v --disable-warnings --cov=app
