name: Python Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Upgrade pip, setuptools and wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Install backend package
      working-directory: ./backend
      run: |
        pip install -e .

    - name: Install testing dependencies
      working-directory: ./backend
      run: |
        pip install pytest pytest-asyncio pytest-cov httpx

    - name: Run lint (flake8)
      working-directory: ./backend
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests
      env:
       PYTHONPATH: ${{ github.workspace }}/backend
      run: |
       pytest backend/tests -v --disable-warnings --cov=app
