name: Python Package using Conda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.11
        activate-environment: base
        environment-file: environment.yml
        use-mamba: true
        mamba-args: "--strict-channel-priority"

    - name: Install editable backend (if any)
      run: conda run -n base pip install -e backend

    - name: Lint with flake8
      run: |
        conda run -n base flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        conda run -n base flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests
      run: |
        export PYTHONPATH=$PWD
        conda run -n base pytest backend/tests -v --disable-warnings
