name: Python Package using Conda

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Set up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      # 3. Install Conda
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.11
          activate-environment: base
          environment-file: environment.yml
          use-mamba: false

      # 4. Lint code with flake8
      - name: Lint with flake8
        run: |
          conda run -n base flake8 backend --count --select=E9,F63,F7,F82 --show-source --statistics
          conda run -n base flake8 backend --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # 5. Run tests with pytest
      - name: Run tests
        env:
          # Dodaj backend u PYTHONPATH da bi 'app' modul bio vidljiv
          PYTHONPATH: ${{ github.workspace }}/backend
        run: |
          conda run -n base pytest backend/tests -v --disable-warnings --cov=app
